apiVersion: v1
kind: Service
metadata:
  name: ui-service-test
  namespace: ui-nginx
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: ui-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  namespace: ui-nginx
  labels:
    app: ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-pod
  template:
    metadata:
      name: ui-pod
      labels:
        app: ui-pod
    spec:
      containers:
        - name: ui
          image: nginx
          ports:
            - containerPort: 80
          env:
          - name: ENVIRONMENT
            value: "staging"
